### ISSUE TITLE
Updating Custom Metadata in a Profile doesn't recognize changes

### ISSUE THREAD

**Issue by moojomoore** [moojomoore/git2kandji#6]
With the latest release with adding custom metadata to profiles, git2kandji doesn't recognize updates to the metadata for profiles due to how the `normalize_xml_content` function is configured which causes the comparison to say nothing has changed in the profile.

**Comment by moojomoore** [comment]
@disenchant - I just came across this and initially thought it only had to do with the `normalize_xml_content` function and was working to correct it. I got it corrected, and then found more:

However, it also seems that Kandji strips the comments out from the profile when we're uploading it, so what is returned is a profile without the custom metadata which then causes the compare function to find that every profile needs an update as the local profile in git has the custom metadata and the one returned from Kandji doesn't have the metadata. 

Wondering if you have any thoughts on how to solve for that? One thought I had was putting the metadata in the `PayloadDescription` key as that seems to come through. One upside to moving it here is nothing would need to change in the `normalize_xml_content` function.

**Comment by moojomoore** [comment]
What's interesting is that the XML Preview shown in Kandji matches what is returned via the API GET endpoint. However, if you use the "Download" button for the profile from within Kandji, it downloads the profile with the comments included.

**Comment by disenchant** [comment]
@moojomoore good catch. We can certainly find a way around this but IMHO this is a bug in Kandji (API not being consistent with WebUI) and I'd recommend to open a bug with them and see if they feel like addressing it. The main reason why I'm hesitant to just add it e.g. into the `PayloadDescription` key is that unlike when using comments to store the information it would actually change the profile.

**Comment by moojomoore** [comment]
@disenchant - Agreed. Ticket submitted to Kandji. I'll let you know what they come back with.

I'm assuming that even if they classify it as a bug that it'll be awhile before it's actually corrected. I'll play around with it some and see what other options I can think up that doesn't involve modifying the profile.

This is more for me to remember to come back to, but something to try:
Compare the custom metadata value to the API response as name and active are both returned there. If they don't match, update. If they do match, skip with no changes.

**Comment by moojomoore** [comment]
Kandji is saying that this is a "feature request" and not a bug 🙃.

I ended up working out the comparison of the custom metadata to the API Response for profiles, I didn't see a reason to change the way we do comparisons for scripts. While I was at that, I added the runs_on values to the metadata to set what platforms to install the profile on.
